### ISSUE TITLE
spinner fills console with `WWWW` in JetBrains console.

### ISSUE THREAD

**Issue by fredliang44** [briandowns/spinner#110]
As I started spinner in Goland, spinner fills console with `WWWW`.

https://user-images.githubusercontent.com/22412638/104083012-df8ad100-5275-11eb-8c44-173e7623e18f.mp4

**Comment by fredliang44** [comment]
But if I started command from iTerm, the problem no longer appears.

**Comment by hardboiledalex** [comment]
Same issue, problem exists for standard Windows terminal since v1.12.0. Rollback to v1.11.1 helps. For macOS iTerm - no problems.

**Comment by briandowns** [comment]
Hmmm, I wonder what the possible commonality between the Goland terminal and the Windows terminal is? I'll checkout a differ between the two releases to see if I see anything obvious. Thanks for reporting this.

**Comment by Jaeyo** [comment]
same problem on windows putty terminal. I also rollback to v1.11.1 and resolved.

**Comment by akshaybabloo** [comment]
Any update on this?

**Comment by 2000Slash** [comment]
Just encountered this on Linux with zsh shell. But only for one line that was longer than my terminal width and had to be wrapped around.

**Comment by Dreamacro** [comment]
@briandowns 
Here's the root cause:
https://github.com/briandowns/spinner/blob/2cb1a331834ae44d9f509fd8f583b41ff5c2ff85/spinner.go#L399-L401

I tried removing this code and it still works fine on macOS iterm2, Terminal, JetBrains terminal and vscode's terminal. I'm not sure what this compatibility is for, maybe a historical reason?
