### ISSUE TITLE
Random character showing up along with spinning wheel character

### ISSUE THREAD

**Issue by budhrg** [briandowns/spinner#50]
Hi,

Thanks for the awesome package. We have using it since quite a while in [minishift](https://github.com/minishift/minishift) to show spinning wheel while a user is waiting for registration process is complete.

 However, there are some random characters showing up when spinning wheel is displayed in eclipse console.

```
Starting local OpenShift cluster using 'virtualbox' hypervisor...
--
Registering machine using subscription-manager
�[37m\|�[0m ��  ���[37m/�[0m ��  ���[37m-�[0m ��  ���[37m\�[0m ��  ���[37m\|�[0m ��  ���[37m/�[0m ��  ���[37m-�[0m ��  ���[37m\�[0m
```

More info here https://github.com/minishift/minishift/issues/1277.

Any idea why we are getting such characters?

**Comment by briandowns** [comment]
I'll take a look today. What character encoding is eclipse using? Can you see if it matches a normal shell and if not, change it?

**Comment by briandowns** [comment]
Make sure encoding is UTF-8

**Comment by budhrg** [comment]
@briandowns , I need to check as I am not working from the eclipse side but CLI(minishift) side. I have informed the devs who are working on eclipse side and might respond here.

**Comment by budhrg** [comment]
> What character encoding is eclipse using? Can you see if it matches a normal shell and if not, change it?

Any idea @mmalina ?

**Comment by gbraad** [comment]
Similar libraries, like `gopkg.in/cheggaaa/pb.v1` do not have this issue. However, I also believe the Eclipse terminal emulation might be at fault here.

**Comment by mmalina** [comment]
@budhrg I have no idea. But with Rob's fix in https://github.com/jbosstools/jbosstools-openshift/pull/1556 we no longer see wrong encoding (at least on Mac, I haven't checked on Windows yet). But we still want to get rid of it, because it's a very very long line:
`Starting local OpenShift cluster using 'xhyve' hypervisor...
Registering machine using subscription-manager
|   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   \   |   /   -   Registration successful [33.6s]
-- Checking OpenShift client ... OK`

OK, aparently here it looks ugly, but in Eclipse it's just a very long sequence of | / - \

**Comment by budhrg** [comment]
@mmalina ,

> OK, aparently here it looks ugly, but in Eclipse it's just a very long sequence of | / - \

There is not a long sequence of |/-\ , for us in shell terminals, that character spins at one place giving spinning wheel look.

**Comment by mmalina** [comment]
@budhrg I know. It works fine when I start minishift from terminal. This is specific to Eclipse only. I guess because the shell is not interactive, it doesn't accept characters such as \r (carriage return) that is needed for such a thing.

**Comment by gbraad** [comment]
If prefix/suffix space and colorization can be disabled, we can probably
just use `[]string{".", " "}` to get a blinking for and a spaced dot `. . .
.` in Eclipse.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by briandowns** [comment]
Before any library code is touched, a better understanding of what Eclipse is doing should be had since this only exists in the Eclipse terminal. The escape codes are for color (if specified) and backspacing over previously printed characters. The former is optional and the latter negates the relevance of the library.  More testing and discover in Eclipse is needed.

**Comment by gbraad** [comment]
The colorization can be disabled by setting the colorfunc?

**Comment by gbraad** [comment]
The eclipse console in non-interactive. It does not operate as a . It is not really a terminal emulator, but more like a log

**Comment by briandowns** [comment]
Correct so you'll not have the same functionality. Maybe http://mihai-nita.net/2013/06/03/eclipse-plugin-ansi-in-console/ ?

**Comment by gbraad** [comment]
I suggested the same. At the moment looking into a way to make it work acceptable, without too many changes. This is why the suggestions also suggested 'workarounds' with minimal impact on our end, and none on your end.

**Comment by gbraad** [comment]
@briandowns 
https://github.com/briandowns/spinner/blob/48dbb65d7bd5c74ab50d53d04c949f20e3d14944/spinner.go#L106-L107

Why is there a space at the end of the formatting?

**Comment by briandowns** [comment]
It's necessary for some of the spinners currently in place and others in the works. Example is the Earth spinner. Without the space, the Earth spinner is only partially visible.

**Comment by briandowns** [comment]
What's the current status of this?

**Comment by mmalina** [comment]
AFAIK, minishift went back to using simple dots for showing progress, they no longer use the spinner.
So a fix is no longer needed. @budhrg can you confirm?

**Comment by gbraad** [comment]
Correct. This issue can be closed.
